# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import factorization_pb2 as factorization__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in factorization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FactorizationServiceStub(object):
    """Définition du service Factorization
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FactorizeStream = channel.stream_stream(
                '/factorization.FactorizationService/FactorizeStream',
                request_serializer=factorization__pb2.FactorRequest.SerializeToString,
                response_deserializer=factorization__pb2.FactorResponse.FromString,
                _registered_method=True)


class FactorizationServiceServicer(object):
    """Définition du service Factorization
    """

    def FactorizeStream(self, request_iterator, context):
        """Mode flux bidirectionnel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FactorizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FactorizeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.FactorizeStream,
                    request_deserializer=factorization__pb2.FactorRequest.FromString,
                    response_serializer=factorization__pb2.FactorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'factorization.FactorizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('factorization.FactorizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FactorizationService(object):
    """Définition du service Factorization
    """

    @staticmethod
    def FactorizeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/factorization.FactorizationService/FactorizeStream',
            factorization__pb2.FactorRequest.SerializeToString,
            factorization__pb2.FactorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
