# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: factorization.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'factorization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x61\x63torization.proto\x12\rfactorization\"\x1f\n\rFactorRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"!\n\x0e\x46\x61\x63torResponse\x12\x0f\n\x07\x66\x61\x63tors\x18\x01 \x03(\x03\x32j\n\x14\x46\x61\x63torizationService\x12R\n\x0f\x46\x61\x63torizeStream\x12\x1c.factorization.FactorRequest\x1a\x1d.factorization.FactorResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factorization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACTORREQUEST']._serialized_start=38
  _globals['_FACTORREQUEST']._serialized_end=69
  _globals['_FACTORRESPONSE']._serialized_start=71
  _globals['_FACTORRESPONSE']._serialized_end=104
  _globals['_FACTORIZATIONSERVICE']._serialized_start=106
  _globals['_FACTORIZATIONSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
